### ISSUE TITLE
点击按钮闪退

### ISSUE THREAD

**Issue by Aarondue** [RuffianZhong/Rx-Mvp#2]
我使用的华为Mate9，报错信息如下：

09-19 15:02:44.052 8694-8694/com.rx.mvp.cn E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.rx.mvp.cn, PID: 8694
                                                             java.lang.NoClassDefFoundError: Failed resolution of: Lcom/networkbench/agent/impl/instrumentation/NBSEventTraceEngine;
                                                                 at com.rx.mvp.cn.MainActivity.onClick(MainActivity.java)
                                                                 at com.rx.mvp.cn.MainActivity_ViewBinding$1.doClick(MainActivity_ViewBinding.java:35)
                                                                 at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                 at android.view.View.performClick(View.java:5646)
                                                                 at android.view.View$PerformClick.run(View.java:22459)
                                                                 at android.os.Handler.handleCallback(Handler.java:761)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                 at android.os.Looper.loop(Looper.java:156)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by RuffianZhong** [comment]
@Aarondue 
主页中的按钮就是一个跳转页面的逻辑，不应该会有什么致命的错误。我查了一下你提供的log。你看看会不会是Android studio 环境导致的。例如：gradle 
参考：http://blog.csdn.net/google_acmer/article/details/54913565
